var times = [
  {'time': '09:00', 'for': 'AM', 'selected': 0},
  {'time': '10:00', 'for': 'AM', 'selected': 0},
  {'time': '11:00', 'for': 'AM', 'selected': 0},
  {'time': '12:00', 'for': 'PM', 'selected': 0},
  {'time': '01:00', 'for': 'PM', 'selected': 0},
  {'time': '02:00', 'for': 'PM', 'selected': 0},
  {'time': '03:00', 'for': 'PM', 'selected': 0},
  {'time': '04:00', 'for': 'PM', 'selected': 0},
  {'time': '05:00', 'for': 'PM', 'selected': 0},
  {'time': '06:00', 'for': 'PM', 'selected': 0},
  {'time': '07:00', 'for': 'PM', 'selected': 0},
  {'time': '08:00', 'for': 'PM', 'selected': 0},
  {'time': '09:00', 'for': 'PM', 'selected': 0},
];
